using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace STP.Domain.LoggingAndReporting
{
    public enum MovementnActionType
    {
        haulier_submit_appl = 499001,
        haulier_withdraw_appl = 499002,
        sort_desktop_submits_appl = 499003,
        sort_desktop_declines_appl = 499004,
        sort_desktop_withdraws_appl = 499005,
        sort_desktop_allocates_proj = 499006,
        sort_desktop_reallocates_proj = 499007,
        sort_receives_appl_from_haul = 499008,
        sort_acknowledges_appl_tohaul = 499009,
        user_logs_in = 499010,
        user_logs_out = 499011,
        hauliers_withdrawal_req_receipt = 499012,
        sort_withdrawal_request_receipt = 499013,
        sort_desk_sends_candroutever_for_check = 499014,
        sort_desk_returns_candver_from_check = 499015,
        sort_desk_distributes_movement_version = 499016,
        user_opens_inbox_item = 499017,
        inbox_item_delivered = 499018,
        outbound_doc_ready_for_delivery = 499019,
        outbound_doc_delivery_failure = 499020,
        user_amends_special_order = 499021,
        user_deletes_special_order = 499022,
        user_revokes_special_order = 499023,
        user_creates_special_order = 499024,
        user_agrees_movement_version = 499025,
        user_unagrees_movement_version = 499026,
        outbound_doc_delivered = 499027,
        user_adds_mtp = 499028,
        user_deletes_mtp = 499029,
        delegation_alert = 499030,
        notification_attempt = 499031,
        admin_create_new_contact = 499032,
        admin_changes_users_detail = 499033,
        admin_deleted_contact_user = 499034,
        new_contact = 499035,
        delete_contacts = 499036,
        amend_contact = 499037,
        sort_desktop_revises_appl = 499038,
        haulier_revises_application = 499039,
        haulier_clones_application = 499040,
        sort_desk_creates_movement_revisions = 499041,
        sort_desk_acknowl_proj_revisions = 499042,
        user_amends_amendment_order = 499043,
        user_creates_amendment_order = 499044,
        user_supersedes_special_order = 499045,
        renotification_attempt = 499046,
        pre_esdal_move_addition_attempt = 499047,
        collaboration_status_check = 499048,
        int_collab_details_amended = 499049,
        outbound_document_retransmitted = 499050,
        transmission_delivered = 499051,
        transmission_delivery_failure = 499052,
        transmission_ready_for_delivery = 499053,
        movement_notified = 499054,
        outbound_document_delivery_retry = 499055,
        transmission_delivery_retry = 499056,
        outbound_document_suppressed = 499057,
        manual_party_added = 499065,
        transmission_status_changed = 499066,
        user_accepted_terms_and_cond = 499067,
        user_accepted_notification_terms_and_cond = 499068,
        notification_collaboration_made = 499069,
        notification_collaboration_viewed = 499070,
        transmission_forwarded = 499058,
        vr1_application_approved = 499059,
        caution_added = 499060,
        caution_deleted = 499061,
        caution_modified = 499062,
        transmission_sent = 499063,
        daily_digest_sent = 499064,
        sort_desk_sends_mov_ver_for_QA_check = 499071,
        sort_desk_returns_mov_ver_from_QA_check = 499072,
        sort_desk_sends_mov_ver_for_final_check = 499073,
        sort_desk_returns_mov_ver_from_final_check = 499074,
        user_creates_candidate_ver_from_revised_app_ver = 499075,
        user_reuse_special_order = 499076,
        haulier_application_removed = 499077,
        notification_process_completed = 499078,
        haulier_notification_renotified = 499079,
        haulier_notification_cloned = 499080,
        haulier_notifcation_revised = 499081,
        haulier_distributed_notification_to_soa = 499082,
        haulier_distributed_notification_to_police = 499083,
        soa_modify_route = 499084,
        police_modify_route = 499085,
        soa_sent_email_to_haulier = 499086,
        police_sent_email_to_haulier = 499087,
        sort_desktop_unwithdraws_application = 499088,
        sort_desktop_unwithdraw = 499089,
        sort_submit_VR1_appl = 499090,
        user_creates_candidate_ver_from_revised_candidate_ver = 499091
    }

    //System events
    public enum SysEventType
    {
        portal_startup = 401001,
        portal_shutdown,
        portal_successful_login,
        portal_failed_login,
        portal_user_logged_out,
        sort_successful_login,
        sort_failed_login,
        sort_user_loggedout,
        password_expired,
        haulier_created_application,
        haulier_submitted_application,
        haulier_withdrew_application,
        haulier_deleted_application,
        sort_created_application,
        sort_declined_application,
        sort_submitted_application,
        sort_withdrew_application,
        sort_deleted_application,
        nack_message_received,
        portal_user_accepted_TsAndCs,
        haulier_amended_preferences,
        soa_amended_preferences,
        content_published,
        content_rollbacked,
        content_updated,
        content_retrieved,
        content_retracted,
        document_downloaded,
        distribution_failure,
        access_status_altered,
        added_contact,
        added_organisation,
        added_user,
        admin_status_altered,
        amended_contact,
        amended_organisation,
        amended_user,
        decline_preregistration,
        decline_registration,
        deleted_contacts,
        deleted_organisations,
        deleted_users,
        mis_daily_stats_collected,
        mis_stats_collection_failure,
        password_changed,
        portal_migration,
        preregistration,
        registration_request,
        reset_password,
        sanction_preregistration,
        sanction_registration,
        publish_full_dataset,
        publish_outline_dataset,
        feedback_failure,

        //Newly updated sysevents on 20-02-2015
        haulier_created_fleet_component = 401055,
        haulier_edited_fleet_component,
        haulier_deleted_fleet_component,
        haulier_added_registration_for_fleet_component,
        haulier_deleted_registration_for_fleet_component,
        haulier_added_axle_details_for_fleet_component,
        haulier_edited_axle_details_for_fleet_component,
        haulier_created_fleet_vehicle,
        haulier_edited_fleet_vehicle,
        haulier_deleted_fleet_vehicle,
        haulier_added_fleet_component_as_config,//created a new component and added it as config.
        haulier_added_new_fleet_component,//created new component inside a config and added it as fleet comp
        haulier_imported_component,
        haulier_deleted_component,
        haulier_added_registration_for_fleet_vehicle,
        haulier_deleted_registration_for_fleet_vehicle,

        sort_saved_so_application,
        sort_created_new_vehicle_for_so_application,
        sort_created_new_configuration_for_so_application,
        sort_imported_component_for_so_application,
        sort_created_component_for_so_application,
        sort_created_axle_for_so_application,
        sort_added_component_to_fleet_for_so_application,
        sort_edited_component_for_so_application,
        sort_replaced_component_for_so_application,
        sort_edited_vehicle_for_so_application,
        sort_deleted_vehicle_for_so_application,
        sort_added_new_vehicle_to_fleet_for_so_application,
        sort_copied_vehicle_for_so_application,
        Sort_imported_vehicle_from_fleet_for_so_application,
        Sort_imported_vehicle_from_previous_movement_for_so_application,
        Sort_created_new_route_by_textual_description_for_so_application,
        Sort_created_new_route_by_start_and_end_point_for_so_application,
        Sort_created_new_route_by_map_for_sort_so_application,
        sort_chose_existing_route_from_library_for_so_application,
        Sort_imported_route_from_previous_movement_for_so_application,
        Sort_edited_route_for_so_application,
        Sort_deleted_route_for_so_application,
        Sort_added_to_route_library_for_so_application,
        Sort_submitted_so_application,
        Sort_saved_vr1_application,
        Sort_created_new_vehicle_for_vr1_application,
        Sort_created_configuration_for_vr1_application,
        Sort_imported_component_for_vr1_application,
        Sort_created_component_for_vr1_application,
        Sort_created_axle_for_vr1_application,
        Sort_added_component_to_fleet_for_vr1_application,
        Sort_edited_component_for_vr1_application,
        Sort_replaced_component_for_vr1_application,
        Sort_edited_vehicle_for_vr1_application,
        Sort_deleted_vehicle_for_vr1_application,
        Sort_added_vehicle_to_fleet_for_vr1_application,
        Sort_copied_vehicle_for_vr1_application,
        Sort_imported_vehicle_from_fleet_for_vr1_application,
        Sort_imported_vehicle_from_previous_movement_for_vr1_application,
        Sort_created_new_route_by_textual_description_for_vr1_application,
        Sort_created_a_new_route_by_start_and_end_point_for_vr1_application,
        Sort_created_a_new_route_by_map_for_vr1_application,
        Sort_chose_existing_route_from_library_for_vr1_application,
        Sort_imported_route_from_previous_movement_for_vr1_application,
        Sort_edited_route_for_vr1_application,
        Sort_deleted_route_for_vr_application,
        Sort_added_route_to_library_for_vr1_application,
        Sort_submitted_vr1_application,
        Haulier_created_notification,
        Haulier_submitted_notification,

        Haulier_created_new_vehicle,
        Haulier_imported_vehicle_from_fleet,
        Haulier_imported_vehicle_from_previous_movement,
        Haulier_deleted_vehicle,
        Haulier_edited_vehicle,
        Haulier_added_vehicle_to_fleet,
        Haulier_copied_vehicle,

        Haulier_created_new_route,
        Haulier_imported_route_from_library,
        Haulier_imported_route_from_previous_movement,
        Haulier_deleted_route,
        Haulier_edited_route,
        Haulier_added_route_to_library,
        Haulier_notification_renotified,
        Haulier_notification_cloned,
        Haulier_notifcation_revised,
        Haulier_notifcation_deleted,
        Haulier_saved_so_application,

        Haulier_created_new_vehicle_for_so_application,
        Haulier_created_configuration_for_so_application,
        Haulier_imported_component_for_so_application,
        Haulier_created_component_for_so_application,
        Haulier_created_axle_for_so_application,
        Haulier_added_component_to_fleet_for_so_application,
        Haulier_edited_component_for_so_application,
        Haulier_replaced_component_for_so_application,
        Haulier_edited_vehicle_for_so_application,
        Haulier_deleted_vehicle_for_so_application,
        Haulier_added_vehicle_to_fleet_for_so_application,
        Haulier_copied_vehicle_for_so_application,
        Haulier_imported_vehicle_from_fleet_for_so_application,
        Haulier_imported_vehicle_from_previous_movement_for_so_application,

        Haulier_created_new_route_by_textual_description_for_so_application,
        Haulier_created_new_route_by_start_and_end_point_for_so_application,
        Haulier_created_new_route_by_map_for_so_application,
        Haulier_imported_existing_route_from_library,
        Haulier_imported_route_from_previous_movement_for_so_application,
        Haulier_edited_route_for_so_application,
        Haulier_deleted_route_for_so_application,
        Haulier_added_route_to_library_for_so_application,
        Haulier_submitted_so_application,
        haulier_saved_vr1_application = 401162,
        /*haulier_saved_so_application,
        haulier_edited_so_application,
        haulier_edited_vr1_application,
        haulier_deleted_so_application,
        haulier_deleted_vr1_application,*/

        Haulier_created_new_vehicle_for_vr1_application,
        Haulier_created_configuration_for_vr1_application,
        Haulier_imported_component_for_vr1_application,
        Haulier_created_component_for_vr1_application,
        Haulier_created_axle_for_vr1_application,
        Haulier_added_component_to_fleet_for_vr1_application,
        Haulier_edited_component_for_vr1_application,
        Haulier_replaced_component_for_vr1_application,
        Haulier_edited_vehicle_for_vr1_application,
        Haulier_deleted_vehicle_for_vr1_application,
        Haulier_added_vehicle_to_fleet_for_vr1_application,
        Haulier_copied_vehicle_for_vr1_application,
        Haulier_imported_vehicle_for_vr1_application,
        Haulier_imported_vehicle_from_previous_movment,

        Haulier_created_new_route_by_textual_description_for_vr1_application,
        Haulier_created_new_route_by_start_and_end_point_for_vr1_application,
        Haulier_created_new_route_by_map_for_vr1_application,
        Haulier_chose_existing_route_from_library_for_vr1_application,
        Haulier_imported_route_from_previous_movement_for_vr1_application,
        Haulier_edited_route_for_vr1_application,
        Haulier_deleted_route_for_vr1_application,
        Haulier_addd_route_to_library_for_vr1_application,
        Haulier_submitted_vr1_application,
        show_sort_project_overview_details,
        bind_sort_application_revisions,
        bind_sort_movment_revisions,
        bind_sort_candidate_route_revisions,
        bind_sort_special_orders,
        allocate_sort_users,
        save_sort_project_details_from_project_overview_tab,
        save_sort_new_candidate_route,
        create_new_revision_from_last_candidate_evision,
        sort_checking_process,
        show_sort_candidate_route,
        show_sort_candidate_route_vehicles,
        create_new_so_movement_version,
        show_movement_summary,
        save_haulier_notes,
        get_haulier_notes,
        get_movement_history_details,
        sort_movement_distribution,
        sort_movement_agree,
        sort_movement_unagree,
        sort_movement_withdraw,
        sort_created_special_order,
        sort_saved_special_order,
        sort_show_special_order,
        sort_deleted_special_order,
        sort_generated_special_order_documents,
        sort_generated_amendment_order,
        sort_revise_so_application,
        Retransmitted_document,
        Retransmit_failed_document,
        View,
        Check_as_Haulier,
        Check_as_SOA,
        Check_as_Police,

        Haulier_created_configuration_for_notification,
        Haulier_imported_component_for_notification,
        Haulier_created_component_for_notification,
        Haulier_created_axle_for_notification,
        Haulier_added_component_to_fleet_for_notification,
        Haulier_edited_component_for_notification,
        Haulier_replaced_component_for_notification,
        Haulier_edited_configuration_for_notification,
        Haulier_edited_axle_for_notification,
        Haulier_edited_configuration_for_vr1_application,
        Haulier_edited_axle_for_vr1_application,
        Haulier_edited_configuration_for_so_application,
        Haulier_edited_axle_for_so_application,
        Haulier_created_component,
        Haulier_edited_component,
        Haulier_notify_so_app,
        Haulier_revised_so_app,
        Haulier_cloned_so_app,
        Haulier_notify_vr1_app,
        Haulier_revised_vr1_app,
        Haulier_cloned_vr1_app,
        Haulier_created_library_route,
        Haulier_edited_library_route,
        Haulier_deleted_library_route,

        haulier_added_registration_for_so_vehicle,
        haulier_added_registration_for_vr1_vehicle,
        haulier_edited_axle_details_for_so_component,
        haulier_edited_axle_details_for_vr1_component,
        sort_edited_axle_details_for_so_component,
        sort_edited_axle_details_for_vr1_component,
        haulier_deleted_registration_for_so_component,
        haulier_deleted_registration_for_vr1_component,
        sort_deleted_registration_for_so_component,
        sort_deleted_registration_for_vr1_component,
        Haulier_replaced_component_for_fleet_vehicle,

        Haulier_created_new_vehicle_for_notification,
        Haulier_imported_vehicle_for_notification,
        Haulier_imported_veh_from_prev_mov_for_notification,
        Haulier_copied_vehicle_for_notification,
        Haulier_created_new_route_by_map_for_notification,
        Haulier_edited_route_for_notification,
        Haulier_imported_route_from_library_for_notification,
        Haulier_addd_route_to_library_for_notification,
        Haulier_deleted_route_for_notification,
        haulier_deleted_registration_for_vr1_vehicle,
        sort_deleted_registration_for_vr1_vehicle,
        haulier_deleted_registration_for_so_vehicle,
        sort_deleted_registration_for_so_vehicle,
        sort_added_registration_for_vr1_vehicle,
        sort_added_registration_for_so_vehicle,
        enabled_user,
        disabled_user,
        sort_deleted_candidate_route,
        sort_unwithdraw
    }
}