name: first test workflow
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  first_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CodeQL
        uses: github/codeql-action/analyze@v2
        
#      - name: Autobuild
#        uses: github/codeql-action/autobuild@v3
           
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: build  # Adjust this to your build output directory
          run: "pwd"
